AWSTemplateFormatVersion: 2010-09-09
Description: cloudformation practice

Parameters:
  System:
    Type: String
  Stage:
    Type: String
  VPCCidrBlock:
    Type: String

Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VPCCidrBlock
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: !Sub ${System}-${Stage}-vpc

Outputs:
  VpcId:
    Value: !Ref VPC
