AWSTemplateFormatVersion: 2010-09-09
Description: Compute Stack

Parameters:
  System:
    Type: String
  Stage:
    Type: String
  SecurityGroupId:
    Type: AWS::EC2::SecurityGroup::Id
  SubnetId:
    Type: AWS::EC2::Subnet::Id
  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
  InstanceProfile:
    Type: String
  InstanceType:
    Type: String
  ImageId:
    Type: AWS::EC2::Image::Id

Resources:
  EC2:
    Type: AWS::EC2::Instance
    CreationPolicy:
      ResourceSignal:
        Timeout: PT5M
    Properties:
      InstanceType: !Ref InstanceType
      IamInstanceProfile: !Ref InstanceProfile
      KeyName: !Ref KeyName
      ImageId: !Ref ImageId
      NetworkInterfaces:
        - AssociatePublicIpAddress: true
          DeviceIndex: 0
          GroupSet:
            - !Ref SecurityGroupId
          SubnetId: !Ref SubnetId
      Tags:
        - Key: Name
          Value: !Sub ${System}-${Stage}-web
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash -xe
          yum update -y
          /opt/aws/bin/cfn-init -s ${AWS::StackId} -r EC2 -c setup --region ${AWS::Region}
          /opt/aws/bin/cfn-signal -e $? --stack ${AWS::StackId} --resource EC2 --region ${AWS::Region}
    Metadata:
      AWS::CloudFormation::Init:
        configSets:
          setup:
            - web
        web:
          packages:
            yum:
              nginx: []
          commands:
            1-uname:
              command: "uname -n > /usr/share/nginx/html/index.html"
          services:
            sysvinit:
              nginx:
                enabled: true
                ensureRunning: true
  EIP:
    Type: AWS::EC2::EIP
    DependsOn: EC2
    Properties:
      InstanceId: !Ref EC2

Outputs:
  PublicIp:
    Value: !GetAtt EC2.PublicIp