AWSTemplateFormatVersion: 2010-09-09
Description: Security Group Stack

Parameters:
  System:
    Type: String
  Stage:
    Type: String
  VpcId:
    Type: AWS::EC2::VPC::Id

Resources:
  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable ssh and web access
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: !Sub ${System}-${Stage}-security-group

Outputs:
  SecurityGroupId:
    Value: !Ref SecurityGroup